services:
  - type: web
    runtime: node
    name: cwf-backend
    env: node
    rootDir: backend
    buildCommand: yarn install && yarn build
    startCommand: yarn start
    plan: free
    envVars:
      - key: PORT
        value: 3000
  - type: web
    runtime: static
    name: cwf-frontend
    rootDir: frontend
    buildCommand: yarn install && yarn build
    staticPublishPath: dist
  - type: cron
    name: db-weekly-backup
    runtime: docker
    schedule: '@weekly'
    dockerfilePath: db-backup/Dockerfile
    envVars: []
databases:
  - type: postgres
    name: cwf-db
    plan: free
    databaseName: cwf